name: flutter_assets_reference_generator
description: Flutter resource reference generation tool.
version: 1.0.1
repository: https://github.com/gjwlfeng/flutter_assets_reference_generator

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  build_config: ^1.1.1
  code_builder: ^4.5.0
  image: ^4.0.17
  dart_style: ^2.1.1
  args: ^2.4.2
  analyzer: ^5.13.0
  built_collection: ^5.1.1
  pubspec_parse: ^1.2.3
  yaml: ^3.1.2
  path: ^1.8.3

executables:
  farg: flutter_assets_reference_generator
